(function(){
const SESSION='porter-auth-user';
function styles(){const s=document.createElement('style');s.textContent=`#porterLogin{position:fixed;inset:0;z-index:99999;background:linear-gradient(180deg,#061426,#071b33);color:#fff;display:flex;align-items:center;justify-content:center;padding:20px;font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}#porterLogin .box{width:min(100%,500px);background:linear-gradient(145deg,#0b2340,#0e2c4f);border:1px solid #1d4b78;border-radius:22px;padding:24px}#porterLogin h1{margin:0 0 6px}#porterLogin p{color:#a9bdd3}#porterLogin select,#porterLogin input{width:100%;padding:14px;margin:8px 0;border-radius:12px;border:1px solid #1d4b78;background:#071b33;color:#fff;font-size:18px}#porterLogin button,.porterLogout{width:100%;border:0;border-radius:12px;background:#22c55e;color:#fff;font-weight:900;padding:13px;margin-top:10px}.porterLogout{background:#12385f;border:1px solid #1d4b78}.loginErr{color:#ff9c9c;min-height:22px}`;document.head.appendChild(s)}
function apiKey(){try{return typeof sbKey==='function'?sbKey():''}catch(e){return ''}}
async function verify(name,pin){const k=apiKey();if(!k)throw new Error('Shared connection unavailable.');const r=await fetch(SUPABASE_REST+'/rpc/verify_porter_pin',{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify({p_name:name,p_pin:pin})});if(!r.ok)throw new Error('Unable to verify PIN.');const rows=await r.json();return rows&&rows[0]}
function applyUser(name){localStorage.setItem('porter-current-person',name);try{currentPerson=name;currentZone=0}catch(e){};if(typeof renderPeople==='function')renderPeople();if(typeof renderTabs==='function')renderTabs();if(typeof renderZone==='function')renderZone();if(typeof renderRounds==='function')renderRounds();if(typeof updateProgress==='function')updateProgress();setTimeout(lock,100)}
function lock(){const name=sessionStorage.getItem(SESSION),sel=document.getElementById('personSelect');if(!name||!sel)return;sel.value=name;sel.disabled=true;const card=sel.closest('.card');if(card&&!card.querySelector('.porterLogout')){const b=document.createElement('button');b.className='porterLogout';b.textContent='Log out';b.onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};card.appendChild(b)}}
async function enter(){const n=document.getElementById('plName').value,p=document.getElementById('plPin').value.trim(),e=document.getElementById('plErr'),b=document.getElementById('plGo');e.textContent='';b.disabled=true;b.textContent='Checking…';try{const u=await verify(n,p);if(!u){e.textContent='Incorrect PIN.';return}sessionStorage.setItem(SESSION,u.name);document.getElementById('porterLogin').remove();applyUser(u.name)}catch(x){e.textContent=x.message||'Login failed.'}finally{b.disabled=false;b.textContent='Sign in'}}
function start(){styles();const saved=sessionStorage.getItem(SESSION);if(saved){applyUser(saved);return}const d=document.createElement('div');d.id='porterLogin';d.innerHTML=`<div class="box"><h1>🧹 Porter Control</h1><p>Sign in with your name and personal PIN.</p><select id="plName"><option>Walter</option><option>Jhomar</option><option>Pat</option><option>Humberto</option><option>Edita</option><option>Renato</option></select><input id="plPin" type="password" inputmode="numeric" maxlength="4" placeholder="4-digit PIN" autocomplete="off"><div id="plErr" class="loginErr"></div><button id="plGo">Sign in</button></div>`;document.body.appendChild(d);document.getElementById('plGo').onclick=enter;document.getElementById('plPin').onkeydown=x=>{if(x.key==='Enter')enter()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();