(function(){
const supervisors=['Renato','Edita','Humberto'];
const porters=['Walter','Jhomar','Pat'];
const allRecipients=['Walter','Jhomar','Pat','Humberto','Edita'];
const STORAGE='https://rtgiaaztmgwqtqpgswvb.supabase.co/storage/v1';
const ZETA_SOUND_KEY='porter-zeta-sound-enabled';
let zetaAudioCtx=null,knownZeta=null,zetaPrimed=false;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function key(){try{return typeof sbKey==='function'?sbKey():localStorage.getItem('porter-supabase-key')||''}catch(e){return ''}}
async function api(path,opt={}){const k=key();if(!k)throw new Error('Shared database not connected');const r=await fetch(SUPABASE_REST+path,Object.assign({},opt,{headers:Object.assign({apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},opt.headers||{})}));if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
function zetaSoundEnabled(){return localStorage.getItem(ZETA_SOUND_KEY)==='1'}
async function unlockZetaAudio(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return false;if(!zetaAudioCtx)zetaAudioCtx=new A();if(zetaAudioCtx.state==='suspended')await zetaAudioCtx.resume();return zetaAudioCtx.state==='running'}catch(e){return false}}
function zetaTone(freq,duration,delay,gain){try{if(!zetaAudioCtx||zetaAudioCtx.state!=='running')return;const o=zetaAudioCtx.createOscillator(),g=zetaAudioCtx.createGain(),t=zetaAudioCtx.currentTime+delay;o.connect(g);g.connect(zetaAudioCtx.destination);o.type='square';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.02);g.gain.setValueAtTime(gain,t+Math.max(.03,duration-.07));g.gain.exponentialRampToValueAtTime(.001,t+duration);o.start(t);o.stop(t+duration+.02)}catch(e){}}
async function zetaAlert(force=false){if(!force&&!zetaSoundEnabled())return;if(!(await unlockZetaAudio()))return;zetaTone(1040,.18,0,.34);zetaTone(1040,.18,.24,.34);zetaTone(780,.25,.50,.32);zetaTone(1180,.38,.82,.38);try{if(navigator.vibrate)navigator.vibrate([220,90,220,90,320])}catch(e){}}
function refreshZetaSoundButton(){const b=document.getElementById('zetaSoundToggle');if(!b)return;b.textContent=zetaSoundEnabled()?'🔊 Zeta sound ON':'🔇 Enable Zeta sound';b.style.background=zetaSoundEnabled()?'#103d2a':'#12385f'}
async function toggleZetaSound(){const enabling=!zetaSoundEnabled();if(enabling){if(!(await unlockZetaAudio())){alert('Zeta sound could not be enabled on this device.');return}localStorage.setItem(ZETA_SOUND_KEY,'1');refreshZetaSoundButton();await zetaAlert(true)}else{localStorage.removeItem(ZETA_SOUND_KEY);refreshZetaSoundButton()}}
async function checkNewZeta(){if(!key()||!currentPerson)return;try{const q='/zetas?assigned_to=eq.'+encodeURIComponent(currentPerson)+'&select=id,created_at&order=created_at.desc&limit=1',rows=await api(q);if(!rows||!rows.length){zetaPrimed=true;return}const id=String(rows[0].id||rows[0].created_at||'');if(zetaPrimed&&knownZeta&&id&&id!==knownZeta)zetaAlert();knownZeta=id;zetaPrimed=true}catch(e){}}
function ensure(){if(document.getElementById('zetasScreen'))return;document.body.insertAdjacentHTML('beforeend',`<div id="zetasScreen" class="full-screen hidden"><div class="screen-inner"><button class="back" id="zetasBack">← Back</button><h1>📋 Zetas</h1><div class="muted" style="margin-bottom:14px">Tasks assigned by management</div><div class="card" id="zetaSoundCard"><strong>Zeta alerts</strong><div class="muted" style="margin-top:5px">Use a different alert sound for new Zeta assignments.</div><button id="zetaSoundToggle" class="back" style="width:100%;margin-top:10px">🔇 Enable Zeta sound</button></div><div id="zetaCreate"></div><div class="card"><strong>Active Zetas</strong><div id="zetaList" style="margin-top:10px"></div></div><div class="card hidden" id="zetaCompletedCard"><strong>Completed Zetas</strong><div class="muted" style="margin-top:5px">Completed tasks are kept separate from active work.</div><div id="zetaCompletedList" style="margin-top:10px"></div></div></div></div><div id="zetaPhotoViewer" class="full-screen hidden" style="z-index:30;background:#061426"><div class="screen-inner"><button class="back" id="zetaPhotoBack">← Back</button><img id="zetaPhotoFull" alt="Zeta attachment" style="display:block;max-width:100%;max-height:82vh;object-fit:contain;margin:20px auto;border-radius:12px"></div></div>`);document.getElementById('zetasBack').onclick=()=>document.getElementById('zetasScreen').classList.add('hidden');document.getElementById('zetaPhotoBack').onclick=()=>document.getElementById('zetaPhotoViewer').classList.add('hidden');document.getElementById('zetaSoundToggle').onclick=toggleZetaSound;refreshZetaSoundButton();if(supervisors.includes(currentPerson))document.getElementById('zetaCompletedCard').classList.remove('hidden')}
function creator(){const box=document.getElementById('zetaCreate');if(!box)return;if(!supervisors.includes(currentPerson)){box.innerHTML='';return}const people=[...new Set([...porters,...supervisors.filter(p=>p!==currentPerson)])];box.innerHTML=`<div class="card"><strong>Create a Zeta</strong><input id="zTitle" placeholder="Task title" style="width:100%;margin-top:10px;padding:11px;border-radius:10px"><textarea id="zDesc" rows="3" placeholder="Instructions" style="width:100%;margin-top:8px;padding:11px;border-radius:10px"></textarea><select id="zAssign" style="width:100%;margin-top:8px;padding:11px;border-radius:10px"><option value="ALL">All team</option>${people.map(p=>`<option value="${p}">${p}</option>`).join('')}</select><select id="zPriority" style="width:100%;margin-top:8px;padding:11px;border-radius:10px"><option>Normal</option><option>High</option><option>Urgent</option></select><input id="zDue" type="date" style="width:100%;margin-top:8px;padding:11px;border-radius:10px"><input id="zFiles" type="file" multiple accept="image/*,.pdf,.doc,.docx" style="width:100%;margin-top:10px"><div class="muted">Optional photos or documents</div><button class="save" id="zSend" style="margin-top:10px">Assign Zeta</button></div>`;document.getElementById('zSend').onclick=createZeta}
async function uploadFiles(zetaId,files){if(!files||!files.length)return;const k=key();for(const f of files){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=zetaId+'/'+Date.now()+'-'+safe;const r=await fetch(STORAGE+'/object/zeta-files/'+encodeURIComponent(path).replace(/%2F/g,'/'),{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':f.type||'application/octet-stream','x-upsert':'false'},body:f});if(!r.ok)throw new Error('Attachment upload failed')}}
async function createOne(payload,files){const rows=await api('/zetas',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(rows&&rows[0]&&files.length)await uploadFiles(rows[0].id,files)}
async function createZeta(){const title=document.getElementById('zTitle').value.trim(),description=document.getElementById('zDesc').value.trim(),choice=document.getElementById('zAssign').value,priority=document.getElementById('zPriority').value,due_date=document.getElementById('zDue').value||null,files=Array.from(document.getElementById('zFiles').files||[]);if(!title){alert('Add a task title.');return}const recipients=choice==='ALL'?allRecipients.filter(p=>p!==currentPerson):[choice],btn=document.getElementById('zSend');btn.disabled=true;try{for(const assigned_to of recipients)await createOne({title,description,created_by:currentPerson,assigned_to,priority,due_date,status:'Pending'},files);document.getElementById('zTitle').value='';document.getElementById('zDesc').value='';document.getElementById('zDue').value='';document.getElementById('zFiles').value='';await load();alert(choice==='ALL'?'Zeta assigned to all team.':'Zeta assigned to '+choice+'.')}catch(e){alert('Could not create Zeta: '+e.message)}finally{btn.disabled=false}}
async function setStatus(id,status){try{await api('/zetas?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,completed_at:status==='Completed'?new Date().toISOString():null})});await load()}catch(e){alert('Could not update Zeta: '+e.message)}}
async function deleteZeta(id,title){if(!supervisors.includes(currentPerson))return;if(!confirm('Delete completed Zeta "'+title+'"?'))return;try{await api('/zetas?id=eq.'+encodeURIComponent(id),{method:'DELETE',headers:{Prefer:'return=minimal'}});await load()}catch(e){alert('Could not delete Zeta: '+e.message)}}
function isImage(name){return /\.(jpg|jpeg|png|gif|webp|heic|heif)$/i.test(name)}
async function fetchObject(path){const k=key(),r=await fetch(STORAGE+'/object/zeta-files/'+encodeURIComponent(path).replace(/%2F/g,'/'),{headers:{apikey:k,Authorization:'Bearer '+k}});if(!r.ok)throw new Error('Could not open attachment');return URL.createObjectURL(await r.blob())}
async function openAttachment(path,image){try{const url=await fetchObject(path);if(image){document.getElementById('zetaPhotoFull').src=url;document.getElementById('zetaPhotoViewer').classList.remove('hidden')}else{window.open(url,'_blank')}}catch(e){alert(e.message)}}
async function loadAttachments(zetaId,box){if(!box)return;try{const k=key(),r=await fetch(STORAGE+'/object/list/zeta-files',{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify({prefix:String(zetaId)+'/',limit:100,offset:0,sortBy:{column:'name',order:'asc'}})});if(!r.ok)return;const files=await r.json();if(!files.length)return;box.innerHTML='<div class="muted" style="margin:10px 0 6px">📎 Attachments</div>'+files.map(f=>{const path=String(zetaId)+'/'+f.name,img=isImage(f.name);return img?`<button class="zeta-attachment" data-path="${esc(path)}" data-image="1" style="display:inline-block;width:auto;padding:0;border:0;background:transparent;margin:6px 8px 6px 0;text-align:left;vertical-align:top"><img alt="Attached photo" style="display:block;width:120px;height:90px;object-fit:cover;border-radius:12px;border:1px solid var(--line)" data-preview="${esc(path)}"><span class="muted" style="display:block;font-size:12px;margin-top:3px">Tap to enlarge</span></button>`:`<button class="back zeta-attachment" data-path="${esc(path)}" data-image="0" style="margin:6px 8px 6px 0">📎 Open ${esc(f.name.replace(/^\d+-/,''))}</button>`}).join('');box.querySelectorAll('.zeta-attachment').forEach(b=>b.onclick=()=>openAttachment(b.dataset.path,b.dataset.image==='1'));for(const img of box.querySelectorAll('[data-preview]')){try{img.src=await fetchObject(img.dataset.preview)}catch(e){img.alt='Photo could not be loaded'}}}catch(e){}}
function renderZeta(z,list,completed=false){const row=document.createElement('div');row.className='review';row.style.marginBottom='10px';row.innerHTML=`<strong>${esc(z.title)}</strong><div class="muted">${esc(z.assigned_to)} · ${esc(z.priority)} · ${esc(z.status)}</div>${z.description?`<div style="margin-top:6px">${esc(z.description)}</div>`:''}${z.due_date?`<div class="muted">Due: ${esc(z.due_date)}</div>`:''}`;const attachments=document.createElement('div');attachments.className='zeta-attachments';row.appendChild(attachments);const actions=document.createElement('div');actions.className='stock-actions';actions.style.marginTop='8px';if(!completed){if(z.status==='Pending')actions.innerHTML+=`<button data-zeta="${z.id}" data-status="In progress">Start</button>`;actions.innerHTML+=`<button data-zeta="${z.id}" data-status="Completed">Complete</button>`}else if(supervisors.includes(currentPerson)){actions.innerHTML=`<button data-delete-zeta="${z.id}">🗑️ Delete</button>`}row.appendChild(actions);list.appendChild(row);actions.querySelectorAll('[data-zeta]').forEach(b=>b.onclick=()=>setStatus(b.dataset.zeta,b.dataset.status));const del=actions.querySelector('[data-delete-zeta]');if(del)del.onclick=()=>deleteZeta(del.dataset.deleteZeta,z.title);loadAttachments(z.id,attachments)}
async function load(){const list=document.getElementById('zetaList');if(!list)return;const completedList=document.getElementById('zetaCompletedList');list.innerHTML='<div class="muted">Loading…</div>';if(completedList)completedList.innerHTML='<div class="muted">Loading…</div>';try{let activeQ='/zetas?status=neq.Completed&select=*&order=created_at.desc';if(!supervisors.includes(currentPerson))activeQ+='&assigned_to=eq.'+encodeURIComponent(currentPerson);const activeRows=await api(activeQ);list.innerHTML='';if(!activeRows||!activeRows.length)list.innerHTML='<div class="muted">No active Zetas.</div>';else for(const z of activeRows)renderZeta(z,list,false);if(supervisors.includes(currentPerson)&&completedList){const completedRows=await api('/zetas?status=eq.Completed&select=*&order=completed_at.desc');completedList.innerHTML='';if(!completedRows||!completedRows.length)completedList.innerHTML='<div class="muted">No completed Zetas.</div>';else for(const z of completedRows)renderZeta(z,completedList,true)}}catch(e){list.innerHTML='<div class="muted">Could not load Zetas: '+esc(e.message)+'</div>';if(completedList)completedList.innerHTML=''}}
window.openZetas=function(){ensure();document.getElementById('zetasScreen').classList.remove('hidden');creator();if(supervisors.includes(currentPerson)){const c=document.getElementById('zetaCompletedCard');if(c)c.classList.remove('hidden')}load()}
function addButton(){if(document.getElementById('openZetasBtn'))return;const grid=document.querySelector('.quick-grid');if(!grid)return;const b=document.createElement('button');b.id='openZetasBtn';b.className='quick wide';b.innerHTML='<strong>📋 Zetas</strong><span>Tasks assigned by management</span><div class="big">Open</div>';b.onclick=window.openZetas;grid.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(addButton,300));else setTimeout(addButton,300);const old=window.renderAll;if(old)window.renderAll=function(){const r=old.apply(this,arguments);setTimeout(addButton,50);return r}
setTimeout(checkNewZeta,1800);setInterval(checkNewZeta,10000);
})();